<a href="https://colab.research.google.com/github/qcnieles-hub/CPE-031-CPE21S2-Visualization-and-Data-Analysis-Nieles/blob/main/Assignment_1_1_Data_Cleaning_with_Python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1.1.

Introduction to Data Cleaning

In [ ]:
from google.colab import drive
drive.mount( '/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

## Objectives:


* Analyze and interpret the structure and content of raw datasets.

* Apply foundational data preprocessing techniques, such as handling missing values and data type conversions.

* Construct a basic data cleaning pipeline to process real-world data efficiently and with reproducibility.

Download the dataset for this activity [here](https://drive.google.com/file/d/1rNS4jxhZXN5LlLCmkoUW02UoT-UGUC46/view?usp=drive_link)

1. Load the dataset then show the first 5 and last 5 datapoints

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/dirty_cafe_sales.csv")

df.head()
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

QUESTION: What Column has numerical values?

The numerical value are,
Quantity,
Price Per Unit ,
Total Spent,

2. Check if there are any missing values in the dataset

In [ ]:
df.describe()
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

  QUESTION: How many columns had missing values? Which column had the highest number of missing values?

7 columns has missing values.

3. Remove unneccessary columns and make sure numerical columns only contain numbers.

In [ ]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [ ]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')

df.dtypes

Transaction ID       object
Item                 object
Quantity            float64
Price Per Unit      float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
dtype: object

In [ ]:
df.dtypes ## Checking the datatype for each column

Item              object
Quantity          object
Price Per Unit    object
Total Spent       object
dtype: object

In [ ]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors='coerce')
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors='coerce')
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors='coerce')

df.head()

     Item  Quantity  Price Per Unit  Total Spent
0  Coffee       2.0             2.0          4.0
1    Cake       4.0             3.0         12.0
2  Cookie       4.0             1.0          NaN
3   Salad       2.0             5.0         10.0
4  Coffee       2.0             2.0          4.0

In [ ]:
df.dtypes ## Checking the datatype for each column

Item               object
Quantity          float64
Price Per Unit    float64
Total Spent       float64
dtype: object

QUESTION: What happened to the object columns?

Numerical columns, the Quantity,Price Per Unit, and the total spent were converted from the object to float64, while the column remain as a object .

4. Remove missing data to ensure all that the final dataset is clean

In [ ]:
df.isna().sum()

Item              333
Quantity          479
Price Per Unit    533
Total Spent       502
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.isna().sum()

Item              0
Quantity          0
Price Per Unit    0
Total Spent       0
dtype: int64

In [ ]:
df.head()

       Item  Quantity  Price Per Unit  Total Spent
0    Coffee       2.0             2.0          4.0
1      Cake       4.0             3.0         12.0
3     Salad       2.0             5.0         10.0
4    Coffee       2.0             2.0          4.0
5  Smoothie       5.0             4.0         20.0

EXPLAIN the process of data cleaning done in the procedure.

The data cleaning process started by checking the dataset for missing value. The unnessary column are removed  and the numirical colunm the Quantity , Price Per Unit, and the total spent it converted to numeric data types.

## Supplemetary Activities

Download the dataset for supplementary activity [here](https://drive.google.com/file/d/1IGm1BrsLlud2QR0Z8_ix4aNw16YclO0E/view?usp=drive_link)



1.   Load the dataset and show the first 5 and last 5 datapoints
2.   Check if there are any missing values in the dataset.
3.   The df must only have Name, Subsribers, Category, and Country. Remove all other columns.
4.   Convert Subscribers to type **int**
5.   Ensure that there are no rows with missing values. (UNKNOWN is counted as a missing value)

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/youtube_subscribers_data.csv")

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/youtube_subscribers_data.csv")
df.head()
df.tail()

,Name,Brand channel,Subscribers (millions),Primary language,Category,Country
45,ARY Digital HD,Yes,59.7,Urdu,Entertainment,Pakistan
46,Fede Vigevani,No,59.4,UNKNOWN,Entertainment,Mexico
47,LooLoo Kids,UNKNOWN,59.3,English,Music,Romania
48,BillionSurpriseToys,Yes,UNKNOWN,English,Entertainment,United States
49,Marshmello,No,57.5,English,Music,United States

1.Load the dataset and show the first 5 and last 5 datapoints

* The dataset was loaded using pd.read_csv() and the head function had display the first 5 of the dataset.While the tail() function displays the last 5 rows of the datasets

In [ ]:
df.isna().sum()

Name                      0
Brand channel             0
Subscribers (millions)    0
Primary language          0
Category                  0
Country                   0
dtype: int64

2. Check if there's any missing values in dataset

In [ ]:
(df == "UNKNOWN").sum()

Name                      0
Brand channel             3
Subscribers (millions)    7
Primary language          3
Category                  0
Country                   0
dtype: int64

3.The df must only have Name, Subsribers, Category, and Country. Remove all other columns.

In [ ]:
df = df[['Name', 'Subscribers (millions)', 'Category', 'Country']]
df.head()

,Name,Subscribers (millions),Category,Country
0,MrBeast,335,Entertainment,United States
1,T-Series,280,Music,India
2,Cocomelon - Nursery Rhymes,UNKNOWN,Education,United States
3,SET India,UNKNOWN,Entertainment,India
4,Vlad and Niki,129,Entertainment,Russia

In [ ]:
df = df[df['Subscribers (millions)'] != 'UNKNOWN']

In [ ]:
df.head()

,Name,Subscribers (millions),Category,Country
0,MrBeast,335,Entertainment,United States
1,T-Series,280,Music,India
4,Vlad and Niki,129,Entertainment,Russia
5,Kids Diana Show,128,Entertainment,United States Ukraine
6,Like Nastya,123,Entertainment,United States Ukraine

In [ ]:
df['Subscribers (millions)'] = pd.to_numeric(df['Subscribers (millions)'])

In [ ]:
df.dtypes

Name                       object
Subscribers (millions)    float64
Category                   object
Country                    object
dtype: object

In [ ]:
df.isna().sum()

Name                      0
Subscribers (millions)    0
Category                  0
Country                   0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, 0 to 49
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    43 non-null     object
 1   Subscribers (millions)  43 non-null     float64
 2   Category                43 non-null     object
 3   Country                 43 non-null     object
dtypes: float64(1), object(3)
memory usage: 1.7+ KB

# Conclusion

Starting out, I struggled to grasp the core concepts of data cleaning and wasn't sure how to approach the process. After searching for guides and following the instructions step-by-step, things began to click.
I successfully loaded and analyzed the dataset by inspecting both the first five and last five data points. Looking at the initial rows helped me understand the column structures and the types of information included, while checking the final rows confirmed the total scope of the entries. This simple step verified that the dataset was properly read and ready for preprocessing.
Beyond just technical execution, this assignment pushed me to think critically about how data cleaning works in practice. Spotting patterns early on made it easier to flag potential issues—like missing values, formatting errors, or unusual entries—before diving into deeper analysis.
first, I found the concept of data cleaning pretty overwhelming and wasn't entirely sure where to begin. After looking up a few guides and walking through the steps, I got the hang of it.

To start, I loaded the dataset and checked the first and last five rows. Looking at the top rows gave me a clear picture of the columns and data types, while the bottom rows confirmed everything loaded completely without missing sections.Taking the time to do this before jumping straight into analysis was a huge help. It forced me to slow down, build my critical thinking around raw data, and spot potential red flags—like weird formats or missing values—right off the bat.

Good job on finishing the activity! Kindly submit your accomplished google colab link and a PDF file of this activity.

https://colab.research.google.com/drive/1FTvQ_uLBaobhuMOYBF7rj5Z-MD4SLE04#scrollTo=wQLlq8Ihgn6x&uniqifier=1